apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billetera-compensar
  description: Aplicación móvil de migración billetera para Compensar
  tags:
    - flutter
    - mobile
    - billetera
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/NikolasSantofimio/documentation/tree/main/components\billeteracompensar
spec:
  type: service
  lifecycle: production
  owner: equipo-movil
  system: billeteras
  consumesApis:
    - appversion
    - sincronizacion
  dependsOn:
    - component:wallet-common
