---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: equipo-1
  description: Equipo de desarrollo de Billetera Compensar
spec:
  type: team
  profile:
    displayName: Equipo 1 - Compensar
    email: equipo1@tudominio.com
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: equipo-2
  description: Equipo de desarrollo de Billetera Cafam
spec:
  type: team
  profile:
    displayName: Equipo 2 - Cafam
    email: equipo2@tudominio.com
  children: []
